### ISSUE TITLE
which methods is used 

### ISSUE THREAD

**Issue by awalece04ku** [abdullah-al-masud/Real-Time-P-QRS-and-T-Wave-Detection-by-QRS-Matched-Filter-Method#1]
Real-Time-P-QRS-and-T-Wave-Detection-by-QRS-Matched-Filter-Method
i want to know in more details

**Comment by abdullah-al-masud** [comment]
You can find the paper in this link:
http://www.iraj.in/journal/journal_file/journal_pdf/11-482-153545859339-43.pdf
